#!/usr/bin/env bash
# core/platform.sh — Platform detection with cache-read fast path
#
# Fast path: source cached platform variables (~1ms)
# Fallback:  detect platform, export variables, write cache

DOTFILES_CACHE_DIR="${HOME}/.dotfiles/cache"
DOTFILES_PLATFORM_CACHE="${DOTFILES_CACHE_DIR}/platform.sh"

# --- Detection (runs only when cache is missing) ---

_dotfiles_detect_platform() {
  # OS
  case "$(uname -s)" in
    Darwin*)       DOTFILES_OS="macos" ;;
    Linux*)        DOTFILES_OS="linux" ;;
    CYGWIN*|MINGW*|MSYS*) DOTFILES_OS="windows" ;;
    *)             DOTFILES_OS="unknown" ;;
  esac

  # Architecture
  DOTFILES_ARCH="$(uname -m)"

  # WSL detection (separate flag, not a platform)
  DOTFILES_WSL=""
  if [[ "$DOTFILES_OS" == "linux" ]] && grep -qi microsoft /proc/version 2>/dev/null; then
    DOTFILES_WSL="true"
  fi

  # Distro (Linux and WSL both use /etc/os-release)
  DOTFILES_DISTRO=""
  DOTFILES_DISTRO_VERSION=""
  if [[ "$DOTFILES_OS" == "linux" ]] && [[ -f /etc/os-release ]]; then
    # shellcheck source=/dev/null
    . /etc/os-release
    DOTFILES_DISTRO="${ID:-unknown}"
    DOTFILES_DISTRO_VERSION="${VERSION_ID:-}"
  fi

  # macOS version
  MACOS_VERSION=""
  if [[ "$DOTFILES_OS" == "macos" ]]; then
    MACOS_VERSION="$(sw_vers -productVersion 2>/dev/null)"
  fi

  # Container detection
  DOTFILES_CONTAINER=""
  if [[ -f /.dockerenv ]] || [[ -f /run/.containerenv ]]; then
    DOTFILES_CONTAINER="true"
  fi

  # Package manager detection
  DOTFILES_PKG_MANAGER=""
  HOMEBREW_PREFIX="${HOMEBREW_PREFIX:-}"
  if [[ "$DOTFILES_OS" == "macos" ]]; then
    if command -v brew &>/dev/null; then
      DOTFILES_PKG_MANAGER="brew"
      if [[ -z "$HOMEBREW_PREFIX" ]]; then
        if [[ "$DOTFILES_ARCH" == "arm64" ]]; then
          HOMEBREW_PREFIX="/opt/homebrew"
        else
          HOMEBREW_PREFIX="/usr/local"
        fi
      fi
    fi
  elif [[ "$DOTFILES_OS" == "linux" ]]; then
    if command -v apt &>/dev/null; then
      DOTFILES_PKG_MANAGER="apt"
    elif command -v dnf &>/dev/null; then
      DOTFILES_PKG_MANAGER="dnf"
    elif command -v pacman &>/dev/null; then
      DOTFILES_PKG_MANAGER="pacman"
    elif command -v zypper &>/dev/null; then
      DOTFILES_PKG_MANAGER="zypper"
    elif command -v yum &>/dev/null; then
      DOTFILES_PKG_MANAGER="yum"
    elif command -v brew &>/dev/null; then
      DOTFILES_PKG_MANAGER="brew"
      if [[ -z "$HOMEBREW_PREFIX" ]]; then
        HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew"
      fi
    fi
  fi
}

_dotfiles_export_platform() {
  export DOTFILES_OS DOTFILES_ARCH DOTFILES_WSL
  export DOTFILES_DISTRO DOTFILES_DISTRO_VERSION
  export DOTFILES_PKG_MANAGER DOTFILES_CONTAINER
  export HOMEBREW_PREFIX MACOS_VERSION
}

_dotfiles_write_platform_cache() {
  mkdir -p "$DOTFILES_CACHE_DIR"
  cat > "$DOTFILES_PLATFORM_CACHE" <<CACHE
# Generated by dotfiles — do not edit
# Re-generate: dotfiles_refresh_platform
DOTFILES_OS="${DOTFILES_OS}"
DOTFILES_ARCH="${DOTFILES_ARCH}"
DOTFILES_WSL="${DOTFILES_WSL}"
DOTFILES_DISTRO="${DOTFILES_DISTRO}"
DOTFILES_DISTRO_VERSION="${DOTFILES_DISTRO_VERSION}"
DOTFILES_PKG_MANAGER="${DOTFILES_PKG_MANAGER}"
DOTFILES_CONTAINER="${DOTFILES_CONTAINER}"
HOMEBREW_PREFIX="${HOMEBREW_PREFIX}"
MACOS_VERSION="${MACOS_VERSION}"
CACHE
}

# --- Public API ---

# Helper functions
is_macos()  { [[ "$DOTFILES_OS" == "macos" ]]; }
is_linux()  { [[ "$DOTFILES_OS" == "linux" ]]; }
is_wsl()    { [[ "$DOTFILES_WSL" == "true" ]]; }
is_arm()    { [[ "$DOTFILES_ARCH" == "arm64" ]] || [[ "$DOTFILES_ARCH" == "aarch64" ]]; }
is_intel()  { [[ "$DOTFILES_ARCH" == "x86_64" ]]; }

# Force re-detect and rewrite cache
dotfiles_refresh_platform() {
  _dotfiles_detect_platform
  _dotfiles_write_platform_cache
  _dotfiles_export_platform
  echo "Platform cache refreshed: ${DOTFILES_PLATFORM_CACHE}"
}

# Formatted display of detected platform info
platform_info() {
  echo "Platform Information:"
  echo "  OS:              ${DOTFILES_OS}"
  echo "  Architecture:    ${DOTFILES_ARCH}"
  [[ -n "$DOTFILES_DISTRO" ]]         && echo "  Distribution:    ${DOTFILES_DISTRO} ${DOTFILES_DISTRO_VERSION}"
  [[ -n "$DOTFILES_WSL" ]]            && echo "  WSL:             yes"
  [[ -n "$MACOS_VERSION" ]]           && echo "  macOS Version:   ${MACOS_VERSION}"
  [[ -n "$DOTFILES_PKG_MANAGER" ]]    && echo "  Package Manager: ${DOTFILES_PKG_MANAGER}"
  [[ -n "$HOMEBREW_PREFIX" ]]         && echo "  Homebrew Prefix: ${HOMEBREW_PREFIX}"
  [[ -n "$DOTFILES_CONTAINER" ]]      && echo "  Container:       yes"
  return 0
}

# --- Load: cache-read fast path, detection fallback ---

if [[ -f "$DOTFILES_PLATFORM_CACHE" ]]; then
  # shellcheck source=/dev/null
  . "$DOTFILES_PLATFORM_CACHE"
  _dotfiles_export_platform
else
  _dotfiles_detect_platform
  _dotfiles_write_platform_cache
  _dotfiles_export_platform
fi
