#!/usr/bin/env bash
# setup/generate-cache.sh — Generate profile cache from ~/.dotfiles.json
#
# Throwaway script — the CLI (Phase 4) replaces this.
# Requires: jq
#
# Usage:
#   ./setup/generate-cache.sh                        # auto-detect profile
#   ./setup/generate-cache.sh /path/to/profile.json  # explicit path
#   DOTFILES_PROFILE=/path ./setup/generate-cache.sh # env var

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# --- Preflight ---

if ! command -v jq &>/dev/null; then
  echo "Error: jq is required but not installed." >&2
  echo "Install: brew install jq / apt install jq / dnf install jq" >&2
  exit 1
fi

# --- Resolve data directory ---

_resolve_data_dir() {
  if [[ -n "${DOTFILES_DATA_DIR:-}" ]]; then
    return 0
  fi
  local candidate
  for candidate in \
    "${HOME}/.dotfiles" \
    "${HOME}/.config/dotfiles" \
    "${HOME}/.local/share/dotfiles" \
  ; do
    if [[ -d "$candidate" ]]; then
      DOTFILES_DATA_DIR="$candidate"
      return 0
    fi
  done
  DOTFILES_DATA_DIR="${HOME}/.dotfiles"
}

_resolve_data_dir
CACHE_DIR="${DOTFILES_DATA_DIR}/cache"
CACHE_FILE="${CACHE_DIR}/profile.sh"

# --- Find profile ---

_find_profile() {
  # Argument takes priority
  if [[ -n "${1:-}" ]]; then
    if [[ -f "$1" ]]; then
      echo "$1"
      return 0
    else
      echo "Error: profile not found: $1" >&2
      exit 1
    fi
  fi

  # Env var
  if [[ -n "${DOTFILES_PROFILE:-}" ]] && [[ -f "$DOTFILES_PROFILE" ]]; then
    echo "$DOTFILES_PROFILE"
    return 0
  fi

  # Search chain
  local candidate
  for candidate in \
    "${HOME}/.dotfiles.json" \
    "${HOME}/.config/dotfiles/profile.json" \
    "${HOME}/.config/dotfiles.json" \
    "${HOME}/.local/dotfiles.json" \
    "${DOTFILES_DIR}/dotfiles.json" \
    "${DOTFILES_DIR}/profiles/default.json" \
  ; do
    if [[ -f "$candidate" ]]; then
      echo "$candidate"
      return 0
    fi
  done

  return 1
}

PROFILE_PATH="$(_find_profile "${1:-}")" || {
  echo "No profile found. Loader will use all-modules default." >&2
  echo "Searched: ~/.dotfiles.json, ~/.config/dotfiles/profile.json, ~/.config/dotfiles.json," >&2
  echo "  ~/.local/dotfiles.json, \$DOTFILES_DIR/dotfiles.json, \$DOTFILES_DIR/profiles/default.json" >&2
  exit 0
}

echo "Profile: ${PROFILE_PATH}"

# --- Parse and generate ---

PROFILE="$(cat "$PROFILE_PATH")"

# Build enabled modules (where shell is true or shorthand true)
ENABLED_MODULES="$(echo "$PROFILE" | jq -r '
  .modules // {} | to_entries[] |
  select(
    (.value == true) or
    (.value | type == "object" and (.shell // false) == true)
  ) | .key
')"

# Build disabled sections
DISABLED_SECTIONS="$(echo "$PROFILE" | jq -r '
  [.modules // {} | to_entries[] |
   select(.value | type == "object") |
   .value.disable // [] | .[]] | .[]
')"

# Build modes
MODE_NAMES="$(echo "$PROFILE" | jq -r '.modes // {} | keys[]')"

mkdir -p "$CACHE_DIR"

{
  echo "# Generated by dotfiles — do not edit"
  echo "# Source: ${PROFILE_PATH}"
  echo "# Generated: $(date -Iseconds)"
  echo ""
  echo "DOTFILES_PROFILE_SOURCE=\"${PROFILE_PATH}\""

  # Enabled modules
  printf "DOTFILES_ENABLED_MODULES=("
  first=true
  while IFS= read -r mod; do
    [[ -z "$mod" ]] && continue
    $first || printf " "
    printf "%s" "$mod"
    first=false
  done <<< "$ENABLED_MODULES"
  echo ")"

  # Disabled sections
  printf "DOTFILES_DISABLED_SECTIONS=("
  first=true
  while IFS= read -r sec; do
    [[ -z "$sec" ]] && continue
    $first || printf " "
    printf "%s" "$sec"
    first=false
  done <<< "$DISABLED_SECTIONS"
  echo ")"

  echo ""
  echo "# Modes — first triggered wins, checked in order"

  # Mode names array
  printf "DOTFILES_MODE_NAMES=("
  first=true
  while IFS= read -r mode; do
    [[ -z "$mode" ]] && continue
    $first || printf " "
    printf "%s" "$mode"
    first=false
  done <<< "$MODE_NAMES"
  echo ")"

  # Per-mode variables
  while IFS= read -r mode; do
    [[ -z "$mode" ]] && continue

    # Triggers
    triggers="$(echo "$PROFILE" | jq -r ".modes[\"$mode\"].env_triggers // [] | .[]")"
    printf "DOTFILES_MODE_%s_TRIGGERS=(" "$mode"
    first=true
    while IFS= read -r t; do
      [[ -z "$t" ]] && continue
      $first || printf " "
      printf "%s" "$t"
      first=false
    done <<< "$triggers"
    echo ")"

    # Include modules
    mods="$(echo "$PROFILE" | jq -r ".modes[\"$mode\"].include_modules // [] | .[]")"
    printf "DOTFILES_MODE_%s_MODULES=(" "$mode"
    first=true
    while IFS= read -r m; do
      [[ -z "$m" ]] && continue
      $first || printf " "
      printf "%s" "$m"
      first=false
    done <<< "$mods"
    echo ")"

    # Never load
    never="$(echo "$PROFILE" | jq -r ".modes[\"$mode\"].never_load // [] | .[]")"
    printf "DOTFILES_MODE_%s_NEVER_LOAD=(" "$mode"
    first=true
    while IFS= read -r n; do
      [[ -z "$n" ]] && continue
      $first || printf " "
      printf "%s" "$n"
      first=false
    done <<< "$never"
    echo ")"
  done <<< "$MODE_NAMES"

} > "$CACHE_FILE"

echo "Cache: ${CACHE_FILE}"
